package onedice.defines

enum class ResErrorType{
    UNKNOWN_GENERATE_FATAL,
    UNKNOWN_COMPLETE_FATAL,
    INPUT_RAW_INVALID,
    INPUT_CHILD_PARA_INVALID,
    INPUT_NODE_OPERATION_INVALID,
    NODE_OPERATION_INVALID,
    NODE_STACK_EMPTY,
    NODE_LEFT_VAL_INVALID,
    NODE_RIGHT_VAL_INVALID,
    NODE_SUB_VAL_INVALID,
    NODE_EXTREME_VAL_INVALID,
    NODE_NONSENSE
}